version: "3.7"
services:
  redis:
    image: ghcr.io/saiemgilani/saiemgilani/gp-redis:latest
    restart: always
    networks:
      - game-on-paper-site
    container_name: redis
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - dd_agent
    links:
      - dd_agent
  cache:
    image: ghcr.io/saiemgilani/saiemgilani/gp-cache:latest
    restart: always
    networks:
      - game-on-paper-site
    container_name: cache
    labels:
      com.datadoghq.ad.logs: '[{"source": "cache", "service": "cache"}]'
    expose:
      - 6380
    ports:
      - 6380:6380
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - dd_agent
    links:
      - dd_agent
  node:
    image: ghcr.io/saiemgilani/saiemgilani/gp-node:latest
    restart: always
    networks:
      - game-on-paper-site
    container_name: node
    labels:
      com.datadoghq.ad.logs: '[{"source": "next.js", "service": "next.js"}]'
    command: ["node","server.js"]
    env_file:
      - .env
    environment:
      RDATA_BASE_URL: http://python:7000/py
    ports:
      - 3000:3000
    depends_on:
      - python
      - redis
      - cache
      - dd_agent
    links:
      - python
      - redis
      - cache
      - dd_agent
    healthcheck:
      test: curl --fail http://node:3000/cfb/scoreboard || exit 1
      interval: 180s
      retries: 5
      start_period: 20s
      timeout: 10s
  python:
    image: ghcr.io/saiemgilani/saiemgilani/gp-python:latest
    restart: always
    networks:
      - game-on-paper-site
    container_name: python
    labels:
      com.datadoghq.ad.logs: '[{"source": "fastapi", "service": "fastapi"}]'
    expose:
      - 7000
    ports:
      - 7000:7000
    healthcheck:
      test: curl --fail http://python:7000/py || exit 1
      interval: 120s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      - dd_agent
    links:
      - dd_agent
  dd_agent:
    image: gcr.io/datadoghq/agent:7
    container_name: dd-agent
    restart: always
    networks:
      - game-on-paper-site
    env_file:
      - .env
    environment:
      DD_API_KEY: "${DD_API_KEY}"
      DD_SITE: "datadoghq.com"
      DD_HOSTNAME: "gameonpaper"
      DD_APM_ENABLED: "true"
      DD_LOGS_ENABLED: "true"
      DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL: "true"
      DD_DOGSTATSD_NON_LOCAL_TRAFFIC: "true"
      DD_CONTAINER_LABELS_AS_TAGS: "true"
      DD_CONTAINER_EXCLUDE: "image:gcr.io/datadoghq/agent*"
      DD_CONTAINER_EXCLUDE_METRICS: "image:gcr.io/datadoghq/agent*"
      DD_CONTAINER_EXCLUDE_LOGS: "image:gcr.io/datadoghq/agent*"
      DD_PROCESS_AGENT_ENABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
        #- /opt/datadog-agent/run:/opt/datadog-agent/run:rw

networks:
  game-on-paper-site: