version: "3.7"
services:
  redis:
    image: ghcr.io/saiemgilani/saiemgilani/gp-redis:latest
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  cache:
    image: ghcr.io/saiemgilani/saiemgilani/gp-cache:latest
    expose:
      - 6380
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  summary:
    image: ghcr.io/akeaswaran/akeaswaran/cfb-team-summaries:latest
    expose:
      - 3000
    ports:
      - 3000:3000
    healthcheck:
      test: curl --fail http://summary:3000/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  node:
    image: ghcr.io/saiemgilani/saiemgilani/gp-node:latest
    command: ["node","server.js"]
    environment:
      RDATA_BASE_URL: "http://python:7000"
    ports:
      - 8000:8000
    depends_on:
      - python
      - summary
      - redis
      - cache
    links:
      - python
      - summary
      - redis
      - cache
    healthcheck:
      test: curl --fail http://localhost:8000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  python:
    image: ghcr.io/saiemgilani/saiemgilani/gp-python:latest
    expose:
      - 7000
    ports:
      - 7000:7000
    healthcheck:
      test: curl --fail http://python:7000/healthcheck || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
