version: "3.7"
services:
  python:
    container_name: python
    build:
      context: ./python
      dockerfile: Dockerfile
      args:
        REDIS_URL: "${REDIS_URL}"
        DD_LOGGING_ENV: "${DD_LOGGING_ENV}"
        DD_HOSTNAME: "${DD_HOSTNAME}"
        DD_PY_SERVICE: "${DD_PY_SERVICE}"
        DD_API_KEY: "${DD_API_KEY}"
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "fastapi", "service": "fastapi"}]'
    env_file:
      - .env
    environment:
      REDIS_URL: "${REDIS_URL}"
      DD_LOGGING_ENV: "${DD_LOGGING_ENV}"
      DD_HOSTNAME: "${DD_HOSTNAME}"
      DD_PY_SERVICE: "${DD_PY_SERVICE}"
      DD_API_KEY: "${DD_API_KEY}"
    expose:
      - 7000
    ports:
      - 7000:7000
    healthcheck:
      test: curl --fail http://python:7000/py/cfb/scoreboard || exit 1
      interval: 180s
      retries: 5
      start_period: 20s
      timeout: 10s
  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile.lru
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'
    expose:
      - 6379
    ports:
      - 6379:6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  cache:
    container_name: cache
    build:
      context: ./redis
      dockerfile: Dockerfile.cache
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "cache", "service": "cache"}]'
    expose:
      - 6380
    ports:
      - 6380:6380
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  node:
    container_name: node
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NODE_ENV: "production"
        RDATA_BASE_URL: "${RDATA_BASE_URL}"
    command: node server.js
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "next.js", "service": "next.js"}]'
    env_file:
      - .env
    environment:
      NODE_ENV: "production"
      RDATA_BASE_URL: "${RDATA_BASE_URL}"
    healthcheck:
      test: curl --fail http://node:3000/cfb/scoreboard || exit 1
      interval: 180s
      retries: 5
      start_period: 20s
      timeout: 10s
    expose:
      - 3000
    ports:
      - 3000:3000
    depends_on:
      - redis
      - cache
      - python
    links:
      - redis
      - cache
      - python

networks:
  game-on-paper-site: