version: "3.9"
services:
  python:
    build:
      context: ./python
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "fastapi", "service": "fastapi"}]'
    expose:
      - 7000
    ports:
      - 7000:7000
    healthcheck:
      test: curl --fail http://python:7000/py || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  redis:
    build:
      context: ./redis
      dockerfile: Dockerfile.lru
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
  cache:
    build:
      context: ./redis
      dockerfile: Dockerfile.cache
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "cache", "service": "cache"}]'
    expose:
      - 6380
    healthcheck:
      test: redis-cli ping || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s

  node:
    command: ["node","server.js"]
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        RDATA_BASE_URL: http://python:7000/py
    restart: unless-stopped
    networks:
      - game-on-paper-site
    labels:
      com.datadoghq.ad.logs: '[{"source": "next.js", "service": "next.js"}]'
    environment:
      RDATA_BASE_URL: http://python:7000/py
    healthcheck:
      test: curl --fail http://localhost:8000/cfb/scoreboard || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - redis
      - cache
      - python
    links:
      - redis
      - cache
      - python

volumes:
  db_cache:
    driver: local
networks:
  game-on-paper-site: