name: deploy

on:
  push:
    branches:
    - main
  schedule:
    - cron: "0 12 * * 1"
  workflow_dispatch:
  workflow_call:

jobs:
  build-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: saiemgilani/game-on-paper
      - name: Publish Node container to GitHub
        uses: mr-smithers-excellent/docker-build-push@v6
        env:
            RDATA_BASE_URL: ${{ secrets.RDATA_BASE_URL }}
        with:
          image: saiemgilani/gp-node
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: ./frontend
          dockerfile: ./frontend/Dockerfile
          tags: latest
  build-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: saiemgilani/game-on-paper
      - name: Publish Python container to GitHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: saiemgilani/gp-python
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: ./python
          dockerfile: ./python/Dockerfile
          tags: latest
  build-redis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: saiemgilani/game-on-paper
      - name: Publish Redis container to GitHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: saiemgilani/gp-redis
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: ./redis
          dockerfile: ./redis/Dockerfile.lru
          tags: latest
      - name: Publish Redis container to GitHub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: saiemgilani/gp-cache
          registry: ghcr.io
          username: ${{ secrets.GH_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          directory: ./redis
          dockerfile: ./redis/Dockerfile.cache
          tags: latest
  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-node
      - build-python
      - build-redis
    steps:
      - uses: actions/checkout@v3
        with:
          repository: saiemgilani/game-on-paper
      - name: Push updated docker-compose override file
        uses: Creepios/sftp-action@v1.0.5
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          localPath: './docker-compose.do.yml'
          remotePath: './docker-compose.yml'
      - name: Deploy package to DigitalOcean
        uses: appleboy/ssh-action@master
        env:
            GITHUB_USERNAME: ${{ secrets.GH_USERNAME }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            DOCKER_COMPOSE_FILE: ${{ env.DOCKER_COMPOSE_FILE }}
            DOCKER_COMPOSE_OVERRIDE_FILE: ${{ env.DOCKER_COMPOSE_OVERRIDE_FILE }}
            DD_API_KEY: ${{ secrets.DD_API_KEY }}
            RDATA_BASE_URL: ${{ secrets.RDATA_BASE_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          command_timeout: 15m
          envs: GITHUB_USERNAME, GITHUB_TOKEN, DOCKER_COMPOSE_FILE, DOCKER_COMPOSE_OVERRIDE_FILE, DD_API_KEY, RDATA_BASE_URL
          script: |
            docker stop $(docker ps -a -q)
            docker system prune --force
            docker login ghcr.io -u $GITHUB_USERNAME -p $GITHUB_TOKEN
            docker-compose pull
            docker-compose -f docker-compose.yml up -d
